baseURL = 'https://haberdashery.online/'
languageCode = 'en-us'
title = 'Haberdashery'
theme = 'PaperMod'

[params]
	ShowReadingTime = true
	ShowShareButtons = false
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
	ShowCodeCopyButtons = false
	ShowFullTextinRSS = true
copyright = 'The Haberdashery — Where odds meet ends, provided by a fool free of charge.'
